# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build:
    defaults:
      run:
        working-directory: projects/cli
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run setup
      - run: npm link
      - run: npm test

  publish-npm:
    defaults:
      run:
        working-directory: projects/cli
    needs: build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run setup
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
